version: '3.8'
services:
  app:
    container_name: golang-app
    build:
      dockerfile: ./deployments/Docker/Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

  db:
    container_name: postgres-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

#  migrator:
#    image: migrate/migrate
#    depends_on:
#      db:
#        condition: service_healthy
#    volumes:
#      - ./schema:/schema
#    command: [ "-path", "/schema", "-database", "${DB_URL}?sslmode=disable", "up" ]
#    networks:
#      - backend

volumes:
  postgres_data:

networks:
  backend: